### ISSUE TITLE
repl.it error

### ISSUE THREAD

**Issue by anchxng** [AkeBoss-tech/CodingClubSubmission-4#1]
ModuleNotFoundError: No module named "pyfiglet"
pls fix i want to play in school

**Comment by anchxng** [comment]
![image](https://user-images.githubusercontent.com/73190725/102225565-5fab5a00-3eb5-11eb-999f-66016971ae4d.png)
image

**Comment by AkeBoss-tech** [comment]
If repl.it isn't working then you can download pyfiglet on your pc by doing and run it on your pc
pip install pyfiglet

The repl link should work. Just reload the page or something to reset the project.

https://repl.it/@AkeBoss/CodingClubSubmission4
